### ISSUE TITLE
why it's not polymer 0.5?

### ISSUE THREAD

**Issue by masterofdaemon** [NicoArbogast/generator-polymer-gulp#7]
Hi, i have seen commit with updated polymer 0.5 in master,when it will be in release? and it's works now? and if it does, how to install master from npm command?

**Comment by frapontillo** [comment]
:+1:

**Comment by narbo** [comment]
Sorry for the delay. I just published v0.4 using polymer 0.5

**Comment by NicoArbogast** [comment]
Sorry for the delay. I just published v0.4 using polymer 0.5
