### ISSUE TITLE
Standalone component

### ISSUE THREAD

**Issue by LM450N** [NicoArbogast/generator-polymer-gulp#9]
What's the right way to create a standalone component ?
I used your generator but I don't know how share my component and how publish the component page.

This generator is more maintained ?  [polymer:seed](https://github.com/yeoman/generator-polymer#seed).

Thank you.

**Comment by NicoArbogast** [comment]
Hi,
This project is no longer maintained for the moment.
Please check the official https://github.com/yeoman/generator-polymer
Thank you
